# fly.toml app configuration file generated for proyectosig on 2023-06-11T17:51:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "proyectosig"
primary_region = "scl"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
 APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  APP_URL = "proyectosig.fly.dev"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

  DB_CONNECTION = "mysql"
  DB_HOST = "databaseproyectsig.internal"
  DB_DATABASE= "some_db"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0



